name: Build and Publish Docker Image to GHCR

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 23 * * 0'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/caddy-custom:latest \
            -t ghcr.io/${{ github.repository_owner }}/caddy-custom:$SHORT_SHA .

      - name: Push Docker images
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          docker push ghcr.io/${{ github.repository_owner }}/caddy-custom:latest
          docker push ghcr.io/${{ github.repository_owner }}/caddy-custom:$SHORT_SHA
